{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Content Pull",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "time() - last_pull" }
   ]
  },
  {
   "title": "Last Backup",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "targets": [
    { "expr": "time() - last_backup" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "100*max(increase(node_cpu_seconds_total{mode!=\"idle\"}[1m])/60)"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": " 100 - 100*node_filesystem_avail_bytes{device=\"/dev/vda1\"}/node_filesystem_size_bytes{device=\"/dev/vda1\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes"
    }
   ]
  },
  {
   "title": "Active nginx connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Traefik Backends Up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "targets": [
    { "expr": "sum(traefik_backend_server_up)", "legendFormat": "Traefik Backends" }
   ]
  },
  {
   "title": "Prometheus Targets Up",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "nginx requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_handled[1m])/60",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "nginx connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active" },
    { "expr": "nginx_connections_reading", "legendFormat": "Reading" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting" },
    { "expr": "nginx_connections_writing", "legendFormat": "Writing" }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "sort(avg(100*increase(container_cpu_usage_seconds_total{name!=\"\"}[1m])/60) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Available system memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "available" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent", "label": "CPU %" }
   ],
   "targets": [
    {
     "expr": "sum(100*increase(node_cpu_seconds_total{mode!=\"idle\"}[2m])/120) by (mode)\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "min(container_memory_usage_bytes - container_memory_cache{name != \"\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"vda\"}[1m])/60",
     "legendFormat": "write"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"vda\"}[1m])/60",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{name!=\"\"})",
     "legendFormat": "Running containers"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])/60",
     "legendFormat": "transmit"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[1m])/60",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "Prometheus Targets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(up)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Traefik Backends Up",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(traefik_backend_server_up)" }
   ]
  },
  {
   "title": "Cronjobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "time() - last_backup", "legendFormat": "Last Backup" },
    { "expr": "time() - last_pull", "legendFormat": "Last Content Pull" }
   ]
  },
  {
   "title": "Traefik Backend Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(traefik_backend_request_duration_seconds_sum/traefik_backend_requests_total) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}